### ISSUE TITLE
Server Crash in media screen

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#136]
I tried uploading random zip file to media library and server crashed

`/app/server` is bound to disk path where data can be saved

```
> sonicjs@0.5.5 start /app

> node server.js



.env-default was copied to .env

✔ Successfully connected to Database!

API key does not start with "SG.".

Website at:  http://localhost:3018

Admin console at:  http://localhost:3018/admin

GraphQL API at:  http://localhost:3018/graphql

ℹ Checking Install...

ℹ Checking Base Content...

✔ Base Content Verified!

✔ Install Verified!

passport.authenticate

logging in: test@*******.net

redirect to /admin

Error: Failed to lookup view "admin/shared-views/admin-role" in views directory "/app/server/themes"

    at Function.render (/app/node_modules/express/lib/application.js:580:17)

    at ServerResponse.render (/app/node_modules/express/lib/response.js:1017:7)

    at /app/server/services/admin.service.js:324:13

Error: Failed to lookup view "admin/shared-views/admin-role" in views directory "/app/server/themes"

    at Function.render (/app/node_modules/express/lib/application.js:580:17)

    at ServerResponse.render (/app/node_modules/express/lib/response.js:1017:7)

    at /app/server/services/admin.service.js:324:13

Error: Failed to lookup view "admin/shared-views/admin-user" in views directory "/app/server/themes"

    at Function.render (/app/node_modules/express/lib/application.js:580:17)

    at ServerResponse.render (/app/node_modules/express/lib/response.js:1017:7)

    at /app/server/services/admin.service.js:324:13

dropzone-upload req.files.file {

  fieldName: 'file',

  originalFilename: 'paint.net.4.3.11.install.anycpu.web.zip',

  path: '/app/server/temp/Vrsp04LsZlpm0qQeFY3WOvc3.zip',

  headers: {

    'content-disposition': 'form-data; name="file"; filename="paint.net.4.3.11.install.anycpu.web.zip"',

    'content-type': 'application/x-zip-compressed'

  },

  size: 825658,

  name: 'paint.net.4.3.11.install.anycpu.web.zip',

  type: 'application/x-zip-compressed'

}

/app/server/services/file.service.js:121

      if (err) throw err;

               ^



[Error: ENOENT: no such file or directory, copyfile '/app/server/temp/Vrsp04LsZlpm0qQeFY3WOvc3.zip' -> '/app/server/assets/uploads/paint.net.4.3.11.install.anycpu.web.zip'] {

  errno: -2,

  code: 'ENOENT',

  syscall: 'copyfile',

  path: '/app/server/temp/Vrsp04LsZlpm0qQeFY3WOvc3.zip',

  dest: '/app/server/assets/uploads/paint.net.4.3.11.install.anycpu.web.zip'

}

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! sonicjs@0.5.5 start: `node server.js`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the sonicjs@0.5.5 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /home/node/.npm/_logs/2022-07-06T17_40_41_110Z-debug.log
```

also if this is my fault I think it would be cool to be able to upload any file via cms to storage cause if you were developing app you could just drop to upload new version and possibly have downloads possible for older version if you as app dev want it...

**Comment by pietru2004** [comment]
also if this is my fault I think it would be cool to be able to upload any file via cms to storage cause if you were developing app you could just drop to upload new version and possibly have downloads possible for older version if you as app dev want it...

**Comment by lane711** [comment]
This is a bug because sonic assumes that you are uploading a backup file. As a work around for uploading zip file, you would have to upload directly to the file system. This will be addressed in a future release.

**Comment by lane711** [comment]
Closing issues related to the legacy version
