### ISSUE TITLE
404 page for admin panel

### ISSUE THREAD

**Issue by Turb0Dizel** [lane711/sonicjs#143]
Correct link
http://localhost:3018/admin/content
Not correct link
http://localhost:3018/admin/content1
CMS reaction:
Error: Failed to lookup view "admin/shared-views/admin-content1" in views directory "c:\OpenServer\domains\sonicjs/server/themes"
    at Function.render (c:\OpenServer\domains\sonicjs\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (c:\OpenServer\domains\sonicjs\node_modules\express\lib\response.js:1017:7)
    at c:\OpenServer\domains\sonicjs\server\services\admin.service.js:324:13

**Comment by lane711** [comment]
Thanks - will resolve this in an upcoming update

**Comment by lane711** [comment]
Closing issues related to the legacy version
