### ISSUE TITLE
categoriesToPost example is broken

### ISSUE THREAD

**Issue by PedroBraude** [lane711/sonicjs#255]
Hello guys! when i click on '''categories-to-posts" i got this:

```SonicJs Error: TypeError: Cannot read properties of undefined (reading 'table')
TypeError: Cannot read properties of undefined (reading 'table')
    at dataRoute (file:///home/mape/Documents/uccaep/sonicjs/src/cms/admin/admin.ts:284:64)
    at null.<anonymous> (file:///home/mape/Documents/uccaep/sonicjs/src/cms/admin/admin.ts:338:35)
    at dispatch (file:///home/mape/Documents/uccaep/sonicjs/node_modules/hono/dist/compose.js:29:23)
    at null.<anonymous> (file:///home/mape/Documents/uccaep/sonicjs/node_modules/hono/dist/compose.js:30:20)
    at null.<anonymous> (file:///home/mape/Documents/uccaep/sonicjs/src/cms/admin/admin.ts:51:9)
    at async dispatch (file:///home/mape/Documents/uccaep/sonicjs/node_modules/hono/dist/compose.js:29:17)
    at null.<anonymous> (async file:///home/mape/Documents/uccaep/sonicjs/.wrangler/tmp/dev-aYv4bs/bundledWorker-0.32029522575725444.js:32796:3)
    at async dispatch (file:///home/mape/Documents/uccaep/sonicjs/node_modules/hono/dist/compose.js:29:17)
    at null.<anonymous> (async file:///home/mape/Documents/uccaep/sonicjs/.wrangler/tmp/dev-aYv4bs/bundledWorker-0.32029522575725444.js:32782:3)
    at async dispatch (file:///home/mape/Documents/uccaep/sonicjs/node_modules/hono/dist/compose.js:29:17)
[wrangler:inf] GET /admin/api/categoriesToPosts 500 Internal Server Error (11ms)
```

I think there is a problem with 'posts.ts'.

When I log from 'categoriesToPosts.ts' all post exports explicitly I get this.

```
console.log({
  posts,
  postsTable,
  postsTableName,
  postsRoute,
  postsDefinition,
  postsRelation,
  postsAccess,
  postsHooks,
  postsFields,
});

log results
{
  posts: {
    access: [Getter],
    definition: [Getter],
    fields: [Getter],
    hooks: [Getter],
    relation: [Getter],
    route: [Getter],
    table: [Getter],
    tableName: [Getter]
  },
  postsTable: undefined,
  postsTableName: undefined,
  postsRoute: undefined,
  postsDefinition: undefined,
  postsRelation: undefined,
  postsAccess: undefined,
  postsHooks: undefined,
  postsFields: undefined,
}
```

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
