### ISSUE TITLE
Filepath invalid - ENOENT: no such file or directory

### ISSUE THREAD

**Issue by tisbris** [lane711/sonicjs#52]
Trying to get this project to load without error.
On startup this error occur.
`EMIT ERROR: Error: ENOENT: no such file or directory, open 'C:\Users\Lenovo\Projects\sonicjs\C:\Users\Lenovo\Projects\sonicjs\server\modules\alert\module.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.getFileSync (C:\Users\Lenovo\Projects\sonicjs\server\services\file.service.js:42:22)
    at C:\Users\Lenovo\Projects\sonicjs\server\services\module.service.js:127:29
    at Array.forEach (<anonymous>)
    at Object.getModuleDefinitionFiles (C:\Users\Lenovo\Projects\sonicjs\server\services\module.service.js:126:11)
    at Object.processModules (C:\Users\Lenovo\Projects\sonicjs\server\services\module.service.js:32:16)
    at Object.functionToExecute (C:\Users\Lenovo\Projects\sonicjs\server\services\module.service.js:17:27)
    at Object.exports.emit (C:\Users\Lenovo\Projects\sonicjs\server\services\emitter.service.js:31:26)
    at C:\Users\Lenovo\Projects\sonicjs\server\boot\routes.js:68:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Lenovo\\Projects\\sonicjs\\C:\\Users\\Lenovo\\Projects\\sonicjs\\server\\modules\\alert\\module.json'
}`

File is located in:
C:\Users\Lenovo\Projects\sonicjs\server\modules\alert\module.json

Not:
C:\Users\Lenovo\Projects\sonicjs\C:\Users\Lenovo\Projects\sonicjs\server\modules\alert\module.json

Maybe this issue is also the root cause for all the other errors recorded when many of the links within the admin section fails to load.
`(node:12072) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'breadCrumbs' of undefined
    at C:\Users\Lenovo\Projects\sonicjs\server\services\admin.service.js:203:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12072) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'systemId' of null
    at Object.exports.getFormJson (C:\Users\Lenovo\Projects\sonicjs\server\services\form.service.js:135:33)
    at Object.exports.getForm (C:\Users\Lenovo\Projects\sonicjs\server\services\form.service.js:88:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\Lenovo\Projects\sonicjs\server\services\admin.service.js:75:27
(node:12072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:12072) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'systemId' of null
    at Object.exports.getFormJson (C:\Users\Lenovo\Projects\sonicjs\server\services\form.service.js:135:33)
    at Object.exports.getForm (C:\Users\Lenovo\Projects\sonicjs\server\services\form.service.js:88:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\Lenovo\Projects\sonicjs\server\services\admin.service.js:158:31
(node:12072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
`

**Comment by lane711** [comment]
Thanks for reporting this. What OS are you running?

**Comment by lane711** [comment]
Also, can you please confirm that you have the latest from master?

**Comment by tisbris** [comment]
I am testing on Win 10 and this is the latest master.

**Comment by lane711** [comment]
Thanks, will take a look and get to you later today

**Comment by lane711** [comment]
Hi @tisbris , this is resolved if you pull latest on master. Please let me know if you run into any additional issues. thx
