### ISSUE TITLE
MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by gh4dp** [lane711/sonicjs#72]
Please help - I need to setup this or other CMS ASAP, and this is my first choice.

I am following "https://sonicjs.com/docs#local-setup" , but it does not instruct to have MongoDB installed locally as a pre-req, so I assume setup is already doing this. Even if I install manually, how do setup connects to this mongo instance ? Need some clarification ASAP. 

Thanks!

Below is error log:

202105281306-msimpg-sonicjs> cd sonicjs/
202105281306-msimpg-sonicjs> npm install

added 546 packages, and audited 547 packages in 7s

8 vulnerabilities (4 moderate, 3 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
202105281306-msimpg-sonicjs> npm start

> graphqlserver@0.3.1 start
> node server.js

Website at:  http://localhost:3018
Admin console at:  http://localhost:3018/admin
GraphQL API at:  http://localhost:3018/graphql
.env-default was copied to .env
/home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/node_modules/mongoose/lib/connection.js:832
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/node_modules/mongoose/lib/connection.js:832:32)
    at /home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/node_modules/mongoose/lib/index.js:345:10
    at /home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/node_modules/mongoose/lib/index.js:1135:10)
    at Mongoose.connect (/home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/node_modules/mongoose/lib/index.js:344:20)
    at Object.<anonymous> (/home/user1/scripts/code-repos/gitHub/sonicjs/sonicjs/server.js:34:10)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  reason: TopologyDescription {
    type: 'Unknown',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        address: 'localhost:27017',
        error: Error: connect ECONNREFUSED 127.0.0.1:27017
            at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 102660531,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}

**Comment by lane711** [comment]
You do need to have mongo installed locally or remotely. You can use mlab or similar service for free.

 Modify the Mongo connection string in the .env file if you need to, but for a typical mongo local install, it should not need to be changed. HTH
