### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by uniforx** [lane711/sonicjs#76]
I installed the latest version 0.4.6 today on two different system. One is Debian Buster (fresh) and one is Win10. But both system had the same issue after "npm start"

> sonicjs@0.4.6 start C:\Users\Name\Downloads\SONIC\sonicjs
> node server.js

C:\Users\Name\Downloads\SONIC\sonicjs\server\services\dal.service.js:211
      content = (await contentRepo.findOne({ where: { id: id } })) ?? {};
                                                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Name\Downloads\SONIC\sonicjs\server\schema\schema.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sonicjs@0.4.6 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonicjs@0.4.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Name\AppData\Roaming\npm-cache\_logs\2021-07-21T16_03_27_565Z-debug.log

**Comment by lane711** [comment]
Thanks for your interest in SonicJs!

I believe this might be a Node version issue - What version of Node.js are you using? 

I'll convert the double question marks to the older syntax and push a fix asap today. I'll keep you posted

**Comment by BiswaViraj** [comment]
@uniforx Can you please mention your Node.js Version?
The syntax used here, i.e Nullish coalescing (??) is supported from node version:14

**Comment by uniforx** [comment]
Surprise .. it´s completely right. I used the v12 and now the v14 works fine.

**Comment by lane711** [comment]
good to hear that resolved it. I also pushed a fix to master for anyone else running an older version of Node
