### ISSUE TITLE
node-express error

### ISSUE THREAD

**Issue by palmtreefrb** [lane711/sonicjs#9]
Website and API work fine, launching Admin I am getting the below errors...

<pre><font color="#4E9A06">[nodemon] starting `node server/server.js`</font>
<font color="#06989A">Website at:  http://localhost:3018</font>
<font color="#06989A">Admin console at:  http://localhost:3018/admin</font>
<font color="#06989A">REST API at:  http://localhost:3018/explorer</font>
<font color="#34E2E2"><b>express</b></font> <font color="#FCE94F"><b>deprecated</b></font> res.send(status): Use res.sendStatus(status) instead <font color="#06989A">server/boot/routes.js:153:13</font>
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT(&apos;set&apos;);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/fredrick/Development/cms/sonicjs/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/fredrick/Development/cms/sonicjs/node_modules/express/lib/response.js:170:12)
    at done (/home/fredrick/Development/cms/sonicjs/node_modules/express/lib/response.js:1004:10)
    at Immediate.&lt;anonymous&gt; (/home/fredrick/Development/cms/sonicjs/node_modules/express-handlebars/lib/utils.js:26:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
<font color="#CC0000">[nodemon] app crashed - waiting for file changes before starting...</font>
</pre>

**Comment by lane711** [comment]
Thanks for trying SonicJs!

Sorry for the late replay. You most likely need to add a .env file to your root folder with the following settings:

RECAPTCHA_SITE_KEY=CHANGEME
SENDGRID_API_KEY=CHANGEME
SENDGRID_PASSWORD=CHANGEME
SENDGRID_USERNAME=CHANGEME
MODE=dev
AMAZONKEY=CHANGEME
AMAZONKEYID=CHANGEME

I'll be handling these settings differently soon, so this is just a temporary workaround.

**Comment by lane711** [comment]
Actually this is now fixed if you get latest from master.

Thanks,
Lane
